import { FileNode, Commit, KeyBinding, Extension } from './types';

export const INITIAL_FILES: FileNode[] = [
  {
    id: '1',
    name: 'main.py',
    language: 'python',
    content: `def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)

# Calculate first 10 numbers
print("Fibonacci Sequence:")
for i in range(10):
    print(f"Fib({i}) = {fibonacci(i)}")
`
  },
  {
    id: '2',
    name: 'hello.py',
    language: 'python',
    content: `print("Hello from Star 975!")
print("Powered by Gemini 2.5 Flash")

names = ["Alice", "Bob", "Charlie"]
for name in names:
    print(f"Greeting {name}...")
`
  },
  {
    id: '3',
    name: 'webapp.py',
    language: 'python',
    content: `# Use the Live Server extension to view this!
html = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: sans-serif; background: #0f172a; color: white; padding: 20px; }
        h1 { color: #3b82f6; }
        .card { background: #1e293b; padding: 20px; border-radius: 8px; margin-top: 20px; }
    </style>
</head>
<body>
    <h1>🐍 Python Web Generator</h1>
    <div class="card">
        <h2>Generated by Python</h2>
        <p>This HTML was printed from a Python script running in the IDE.</p>
        <p>Time: <b>{time}</b></p>
    </div>
</body>
</html>
"""

import datetime
print(html.replace("{time}", str(datetime.datetime.now())))
`
  }
];

export const INITIAL_COMMITS: Commit[] = [
  {
    hash: 'init001',
    message: 'Initial commit',
    timestamp: Date.now() - 100000,
    files: JSON.parse(JSON.stringify(INITIAL_FILES)), // Deep copy
    author: 'System'
  }
];

export const DEFAULT_KEYBINDINGS: KeyBinding[] = [
  { id: '1', actionId: 'run', label: 'Run Code', keys: 'Ctrl+Enter' },
  { id: '2', actionId: 'focus_git', label: 'Commit / Focus Git', keys: 'Ctrl+G' },
  { id: '3', actionId: 'explain', label: 'AI Explain Code', keys: 'Ctrl+E' },
  { id: '4', actionId: 'fix', label: 'AI Fix Code', keys: 'Ctrl+.' },
  { id: '5', actionId: 'toggle_sidebar', label: 'Toggle Sidebar', keys: 'Ctrl+B' },
];

export const AVAILABLE_EXTENSIONS: Extension[] = [
  {
    id: 'prettier-python',
    name: 'Prettier - Python',
    description: 'Code formatter using Gemini AI to beautify your Python scripts.',
    icon: 'AlignLeft',
    version: '1.0.0',
    installed: false
  },
  {
    id: 'live-server',
    name: 'Live Server',
    description: 'Launch a local development server with live reload feature for static & dynamic pages.',
    icon: 'Radio',
    version: '2.1.0',
    installed: false
  },
  {
    id: 'material-icons',
    name: 'Material Icon Theme',
    description: 'Get the Material Design icons in your file explorer.',
    icon: 'Folder',
    version: '4.3.0',
    installed: true
  }
];

export const SYSTEM_INSTRUCTION_RUNNER = `
You are a Python 3.x code interpreter simulator. 
Your goal is to predict and output EXACTLY what the provided Python code would print to stdout.
- Do NOT provide explanations.
- Do NOT include markdown formatting like \`\`\` or code blocks in the output unless the code itself prints them.
- If there is a syntax error or runtime error, output the error message exactly as a Python interpreter would.
- If the code has no output, return an empty string.
`;

export const SYSTEM_INSTRUCTION_HELPER = `
You are an expert Python Senior Engineer.
Your goal is to assist the user by explaining code or fixing bugs.
- Keep responses concise and helpful.
- Use Markdown for formatting.
`;

export const SYSTEM_INSTRUCTION_COMPLETION = `
You are a fast, low-latency Python code completion engine.
Your goal is to provide the next immediate code characters or lines based on the input context.
- Input provided is the code found *before* the cursor.
- Return ONLY the completion text. 
- Do NOT wrap in markdown or code blocks.
- Do NOT repeat the input code.
- If the code is complete or valid as-is, return an empty string.
- Keep completions short (typically 1 line, max 3 lines).
- Do not provide conversational text.
`;

export const SYSTEM_INSTRUCTION_CHAT = `
You are Star 975 Copilot, an expert Python programming assistant integrated into an IDE.
- You have access to the user's current open file content (provided in context).
- Answer questions about the code, help debug, or write new code.
- Keep answers concise and relevant to software development.
- Use markdown for formatting. 
- Always wrap code in \`\`\`python ... \`\`\` blocks.
`;

export const SYSTEM_INSTRUCTION_FORMATTER = `
You are a Python code formatter (like Black or autopep8).
- Receive Python code as input.
- Return ONLY the formatted code.
- strictly adhere to PEP 8 standards.
- Do not add markdown backticks. Return raw code.
- Do not add comments or explanations.
`;